-- DB, WH, SCHEMAS SETUP

CREATE OR REPLACE DATABASE SF_KAFKA_DB;
CREATE OR REPLACE WAREHOUSE SF_KAFKA_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
CREATE OR REPLACE SCHEMA SF_KAFKA_DB.SF_KAFKA_SCHEMA;
CREATE OR REPLACE SCHEMA SF_KAFKA_DB.STREAMING;

-- SERVICE ROLE/USER CREATION

CREATE OR REPLACE ROLE SF_KAFKA_SYSADMIN;
GRANT ROLE SF_KAFKA_SYSADMIN TO ROLE SYSADMIN;

CREATE USER IF NOT EXISTS KAF_SVC_ACC
    TYPE = SERVICE
    DEFAULT_ROLE = SF_KAFKA_SYSADMIN
    DEFAULT_WAREHOUSE = SF_KAFKA_WH;
GRANT ROLE SF_KAFKA_SYSADMIN TO USER KAF_SVC_ACC ;

GRANT ROLE SF_KAFKA_SYSADMIN TO USER JIANSF1;

SHOW GRANTS OF ROLE SF_KAFKA_SYSADMIN;

-- ASSIGN PUBLIC KEY TO SERVICE ACCOUNT

ALTER USER KAF_SVC_ACC SET RSA_PUBLIC_KEY = 
'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvwM86gQWIni2DfAZq40W
xHS0BWzfI0jQlVVOpB4Cgp1U4Qut6YSttXcTFXzbrtQzEVy8E80ulBwKc4iwuh0f
MSkxEVJhfylhw7EO4RMRjlS5pAPoU/K26eWrtZVgnb8wz/Yeg4+MqqeHghIN0u61
fRkfwGTgHfpSqao+4QQFXP7O+SUmqBZQhtIVF4/YseafLiv8IiVBxQpnuFGq6/N+
B8th47Mj/vf8Sq3NtN2fAQvAkg3W5Vgwu+7chTRDxB8QiY/a3seKbw4pXExwRSYq
NviPs6fm60G5Vw68k8eBP11fULbpgGnXqN4zF6OfJaUKPn6GevLgaZrtKNXb1ZK5
CQIDAQAB';

DESC USER KAF_SVC_ACC;
-- GRANTS TO ROLE

GRANT OWNERSHIP ON DATABASE SF_KAFKA_DB TO SF_KAFKA_SYSADMIN ;
GRANT OWNERSHIP ON SCHEMA SF_KAFKA_DB.SF_KAFKA_SCHEMA TO SF_KAFKA_SYSADMIN ;
GRANT OWNERSHIP ON SCHEMA SF_KAFKA_DB.STREAMING TO SF_KAFKA_SYSADMIN ;
GRANT USAGE ON WAREHOUSE SF_KAFKA_WH TO SF_KAFKA_SYSADMIN;

-- DROP ORDERS_RAW FROM SF_KAFKA_SCHEMA AND RECREATE IN STREAMING SCHEMA

DROP TABLE SF_KAFKA_DB.SF_KAFKA_SCHEMA.ORDERS_RAW;

-- TABLE CREATION FOR STREAMING SCHEMA

CREATE OR REPLACE TABLE SF_KAFKA_DB.STREAMING.ORDERS_RAW(
  ORDER_ID   STRING,
  CUSTOMER   STRING,
  AMOUNT     NUMBER(10,2),
  STATUS     STRING,
  CREATED_AT TIMESTAMP_NTZ
);

-- ACCOUNT LOCATOR
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() AS ACCOUNT_IDENTIFIER; -- HJYHXGL-KF41693

SELECT * FROM SF_KAFKA_DB.STREAMING.ORDERS_RAW;

