CREATE OR REPLACE DATABASE SF_KAFKA_DB;
CREATE OR REPLACE WAREHOUSE SF_KAFKA_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
CREATE OR REPLACE SCHEMA SF_KAFKA_DB.SF_KAFKA_SCHEMA;

CREATE OR REPLACE ROLE SF_KAFKA_SYSADMIN;
GRANT ROLE SF_KAFKA_SYSADMIN TO ROLE SYSADMIN;

GRANT OWNERSHIP ON DATABASE SF_KAFKA_DB TO SF_KAFKA_SYSADMIN ;
GRANT OWNERSHIP ON SCHEMA SF_KAFKA_DB.SF_KAFKA_SCHEMA TO SF_KAFKA_SYSADMIN ;

